---
# tasks file for docker-consul
- name: create-consul data dir
  file: path="{{consul_data_dir}}" state=directory
- name: create-consul conf dir
  file: path="{{consul_conf_dir}}" state=directory
- name: create consul config
  template: src="consul-config.json.j2" dest="{{consul_conf_dir}}/consul-config.json"
- name: create consul server
  docker_container:
    name: "consulserver"
    state: started
    recreate: yes
    image: "master.swarm:5000/rattermeyer/consul"
    volumes:
      - "{{consul_conf_dir}}:/config"
      - "{{consul_data_dir}}:/data"
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command:
      - "agent"
      - "-config-dir=/config"
      - "-data-dir=/data"
