---
# tasks file for docker-images
- git: repo=https://github.com/rattermeyer/dockerfiles.git
       dest=/srv/dockerfiles

- name: Build images and push it to a private repo
  docker_image:
    path: "/srv/dockerfiles/{{item.path}}"
    name: "{{item.name}}"
    repository: "{{item.repo | default(omit)}}"
    pull: false
    tag: latest
  with_items:
    - {path: "base/alpine", name: "{{docker_repository}}/rattermeyer/alpine", repo: "{{docker_repository}}/rattermeyer/alpine"}
    - {path: "base/alpine", name: "rattermeyer/alpine", repo: "rattermeyer/alpine"}
    - {path: "consul", name: "{{docker_repository}}/rattermeyer/consul", repo: "{{docker_repository}}/rattermeyer/consul"}
    - {path: "consul", name: "rattermeyer/consul", repo: "rattermeyer/consul"}

#- name: build images
#  command: docker build --tag "{{docker_repository}}/rattermeyer/alpine":latest /srv/ dockerfiles/base/alpine
#- command: docker build --tag "{{docker_repository}}/rattermeyer/consul":latest /srv/dockerfiles/consul
#- command: docker build --tag "{{docker_repository}}/rattermeyer/vault":latest /srv/dockerfiles/vault
