---
# tasks file for docker-images
- git: repo=https://github.com/rattermeyer/dockerfiles.git
       dest=/srv/dockerfiles

#- name: Build alpine base image and push it to a private repo
#  docker_image:
#    path: /srv/dockerfiles/base/alpine
#    name: rattermeyer/alpine
#    repository: master:5000/rattermeyer/alpine
#    tag: latest
#    state: present
#
#- name: Build consul image and push it to a private repo
#  docker_image:
#    path: /srv/dockerfiles/consul
#    name: rattermeyer/consul
#    repository: master:5000/rattermeyer/consul
#    tag: latest
#    state: present
#
- name: build images
  command: docker build --tag "{{docker_repository}}/rattermeyer/alpine":latest /srv/dockerfiles/base/alpine
- command: docker build --tag "{{docker_repository}}/rattermeyer/alpine":latest /srv/dockerfiles/consul

- name: push to repo
  command: docker push {{item}}
  with_items:
    - "{{docker_repository}}/rattermeyer/alpine"
    - "{{docker_repository}}/rattermeyer/consul"
