docker_registry: "master1.swarm:5000"
docker_opts: "--tlsverify --tlscacert=/opt/certs/ca/certs/ca-root.pem --tlscert=/opt/certs/ssl_certs/docker-registry-cert.pem --tlskey=/opt/certs/ssl_certs/docker-registry.key -H unix:// -H tcp://0.0.0.0:2375 --dns 192.168.56.10 --dns 8.8.8.8 --dns 8.8.4.4 --insecure-registry {{docker_registry}}"

apt_repository_flavor: experimental
