swarm_advertise_ip: "{{hostvars[inventory_hostname]['ansible_'+ consul_interface]['ipv4']['address']}}"

swarm_command:
  - "manage"
  - "--replication"
  - "--advertise"
  - "{{swarm_advertise_ip}}:12375"
  - "consul://{{consul_address}}"
