---
# tasks file for custom-certificates
- name: create CA dir
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{ca_dir}}"
    - "{{ca_dir}}/private"
    - "{{ca_dir}}/certs"
    - "{{ca_dir}}/newcerts"
    - "{{cert_dir}}/public"
    - "{{cert_dir}}/private"
- file:
    path: "{{item}}"
    state: touch
  with_items:
    - "{{ca_dir}}/database.txt"
    - "{{ca_dir}}/database.txt.attr"
- name: create CA config
  template:
    src: "caconfig.conf.j2"
    dest: "{{ca_dir}}/caconfig.conf"
- name: Create Serial file
  lineinfile:
    line: "01\n"
    dest: "{{ca_dir}}/serial"
    create: True
    state: present

- name: Create CA key
  shell: >
    openssl req -new -x509 -days 3650
    -config {{ca_dir}}/caconfig.conf -keyform PEM -keyout {{ca_dir}}/private/cakey.pem -outform PEM -out {{ca_dir}}/certs/careq.pem
    -passin pass:test123 -passout pass:test123 -subj "/C=DE/ST=NRW/L=Dorsten/O=DevOps Architect/OU=IT Dept/CN=rattermeyer.de/E=cert@rattermeyer.de"
- name: Create CA
  shell: >
    openssl ca -batch -passin pass:test123 -create_serial -out {{ca_dir}}/certs/cacert.pem -days 365 -keyfile {{ca_dir}}/private/cakey.pem -selfsign -config {{ca_dir}}/caconfig.conf -infiles {{ca_dir}}/certs/careq.pem -subj "/C=DE/ST=NRW/L=Dorsten/O=DevOps Architect/OU=IT Dept/CN=rattermeyer.de/E=cert@rattermeyer.de"
- name: Create priv key
  shell: openssl genrsa -out {{cert_dir}}/private/server_key.pem 4096
- name: Create cert request
  shell: >
    openssl req -new -key {{cert_dir}}/private/server_key.pem -out {{cert_dir}}/server-req.pem -passin pass:test123
    -subj "/C=DE/ST=NRW/L=Dorsten/O=DevOps Architect/OU=IT Dept/CN=rattermeyer.de"
- name: Sign cert
  shell: >
    openssl x509 -days 3650 -CA {{ca_dir}}/certs/cacert.pem -CAkey {{ca_dir}}/private/cakey.pem -req -in {{cert_dir}}/server-req.pem -outform PEM -out {{cert_dir}}/public/cert.pem -CAserial {{ca_dir}}/serial -passin pass:test123
