- name: test if cert exists already
  stat: path="{{cert_dir}}/public/{{item.name}}-cert.pem"
  register: cert_exists

- block:
  - name: templating request
    template:
      src: "req.conf.j2"
      dest: "{{cert_dir}}/{{cert.name}}-req.conf"
  - name: Create priv key
    shell: openssl genrsa -out {{cert_dir}}/private/{{cert.name}}.key 4096
  - name: Create cert request
    shell: >
      openssl req -new -key {{cert_dir}}/private/{{cert.name}}.key -out {{cert_dir}}/{{cert.name}}.csr -passin pass:{{cert.key_pass}}
      -config "{{cert_dir}}/{{cert.name}}-req.conf"
  - name: Sign cert
    shell: >
      openssl x509 -days 365 -CA {{ca_dir}}/certs/ca-root.pem -CAkey {{ca_dir}}/private/ca-key.pem -req -in {{cert_dir}}/{{cert.name}}.csr  -extensions server_cert -extfile {{ca_dir}}/caconfig.conf -outform PEM -out {{cert_dir}}/public/{{cert.name}}-cert.pem -CAserial {{ca_dir}}/serial -passin pass:{{cert.key_pass}}
  - name: Create PKCS 12
    shell:
      openssl pkcs12 -export -clcerts -in {{cert_dir}}/public/{{cert.name}}-cert.pem -inkey {{cert_dir}}/private/{{cert.name}}.key -out {{cert_dir}}/private/{{cert.name}}.p12 -passout pass:{{cert.key_pass}}
    when: cert.isClient is defined and cert.isClient == True
  - name: Create Combined Key / Cert
    shell:
      openssl pkcs12 -in {{cert_dir}}/private/{{cert.name}}.p12 -out {{cert_dir}}/private/{{cert.name}}-combined.pem -clcerts -passin pass:{{cert.key_pass}} -passout pass:{{cert.key_pass}}
    when: cert.isClient is defined and cert.isClient == True
  when: cert_exists.stat.exists == False
