---
# tasks file for dnsmasq
- name: install dnsmasq
  apt: name=dnsmasq state=present
  notify: ['Test and restart dnsmasq']
- name: update hosts
  lineinfile: dest=/etc/hosts line="{{item}}"
  with_items: "{{hosts_entries|default([])}}"
  notify: ['Test and restart dnsmasq']
- name: update dnsmasq.conf
  lineinfile: dest=/etc/dnsmasq.conf line="{{item}}"
  with_items: "{{dnsmasq_conflines|default([])}}"
  notify: ['Test and restart dnsmasq']
