---
- hosts: controller
  roles:
    - role: custom-certificates
      certs:
        - name: "docker-registry"
          lifetime: 365
          key_pass: "test123"
          subject: "/C=DE/ST=NRW/L=Dorsten/O=DevOps Architect/OU=Registry/CN=registry.rattermeyer.de"
          dn: "/C=DE/ST=NRW/L=Dorsten/O=DevOps Architect/OU=Registry/CN=registry.rattermeyer.de"
          dn:
            country: DE
            state: NRW
            locality: Dorsten
            organization: DevOps Architect
            orgunit: Registry
            cn: registry.rattermeyer.de
        - name: "docker-daemon"
          lifetime: 365
          key_pass: "test123"
          subject: "/C=DE/ST=NRW/L=Dorsten/O=DevOps Architect/OU=Daemon/CN=*.swarm"
          dn:
            country: DE
            state: NRW
            locality: Dorsten
            organization: DevOps Architect
            orgunit: docker-daemon
        - name: "docker-client"
          lifetime: 365
          key_pass: "test123"
          subject: "/C=DE/ST=NRW/L=Dorsten/O=DevOps Architect/OU=Daemon/E=docker-client@swarm.local"
          dn:
            country: DE
            state: NRW
            locality: Dorsten
            organization: DevOps Architect
            orgunit: docker-client
          extendedKeyUsage: clientAuth,emailProtection
          isClient: True
