---
- hosts: controller
  roles:
    - role: custom-certificates
      ca_dir: /opt/certs/ca
      cert_dir: /opt/certs/ssl_certs
      certs:
        - name: "docker-registry"
          lifetime: 365
          key_pass: "test123"
          dn:
            country: DE
            state: NRW
            locality: Dorsten
            organization: DevOps Architect
            orgunit: Registry
            cn: registry.rattermeyer.de
        - name: "docker-daemon"
          lifetime: 365
          key_pass: "test123"
          dn:
            country: DE
            state: NRW
            locality: Dorsten
            organization: DevOps Architect
            orgunit: docker-daemon
          ip_alt_names:
            - 192.168.56.11
            - 192.168.56.12
            - 192.168.56.13
            - 192.168.56.21
            - 192.168.56.22
            - 192.168.56.23
        - name: "docker-client"
          lifetime: 365
          key_pass: "test123"
          dn:
            country: DE
            state: NRW
            locality: Dorsten
            organization: DevOps Architect
            orgunit: docker-client
          extendedKeyUsage: clientAuth,emailProtection
          isClient: True
