---
- hosts: dockerhosts
  gather_facts: false
  tasks:
    - apt: upgrade=dist update_cache=yes
  roles:
    - { role: docker-ubuntu, docker_group_members: ["vagrant"]}
  tags:
    - docker

- hosts: dockerregistry
  gather_facts: false
  roles:
    - docker-registry
    - docker-images
  tags:
    - docker-registry
    - docker-images

- hosts: all
  gather_facts: false
  roles:
    - dnsmasq
  tags:
    - dnsmasq

- hosts: consulserver
  gather_facts: false
  roles:
    - docker-consul
  tags:
    - consul

- hosts: swarmhosts
  gather_facts: false
  roles:
    - docker-swarm
  tags:
    - swarm

- hosts: vaults
  roles:
    - docker-vault
  tags:
    - vault
