---
- hosts: dockerhosts
  tasks:
    - apt: upgrade=dist update_cache=yes
  roles:
    - { role: docker-ubuntu, docker_group_members: ["vagrant"]}
  tags:
    - docker

- hosts: all
  gather_facts: false
  roles:
    - dnsmasq
  tags:
    - dnsmasq

- hosts: dockerregistry
  gather_facts: false
  roles:
    - { role: docker-registry, tags: ['docker-registry']}
    - { role: docker-images, tags: ['docker-images']}

- hosts: consulserver
  gather_facts: false
  roles:
    - docker-consul
  tags:
    - consul

- hosts: swarmhosts
  gather_facts: false
  roles:
    - docker-swarm
  tags:
    - swarm

- hosts: vaults
  roles:
    - docker-vault
  tags:
    - vault
