- include: swarm.yml

- hosts: all
  tasks:
    - name: install collectd
      apt: name=collectd install_recommends=true state=present
    - name: configuration
      template: src="templates/network.conf.j2" dest="/etc/collectd/collectd.conf.d/network.conf"
      notify: restart collectd
  tags:
    - collectd
    - cadvisor
  handlers:
    - name: restart collectd
      service: name=collectd state=restarted


- hosts: influxdb
  roles:
    - docker-influxdb

- hosts: swarmhosts
  tasks:
    - name: install cadvisor
      docker_container:
        name: "cadvisor"
        image: "google/cadvisor:latest"
        restart_policy: always
        restart: true
        volumes:
          - "/\\:/rootfs:ro"
          - "/var/run:/var/run:rw"
          - "/sys:/sys:ro"
          - "/var/lib/docker/:/var/lib/docker:ro"
        ports:
          - "8080:8080"
        command: ["-storage_driver=influxdb", "-storage_driver_db=cadvisor", "-storage_driver_host=influxdb.swarm:8086"]
  tags: cadvisor
- hosts: grafana
  tasks:
    - name: install grafana
      docker_container:
        name: grafana
        image: grafana/grafana
        ports:
          - "3000:3000"
#
#- hosts: all
#    - name: install prometheus node-exporter
