- include: swarm.yml

- hosts: all
  tasks:
    - name: install collectd
      apt: name=collectd install_recommends=true state=present
    - name: configuration
      template: src="templates/network.conf.j2" dest="/etc/collectd/collectd.conf.d/network.conf"
      notify: restart collectd
  tags:
    - collectd
    - cadvisor
  handlers:
    - name: restart collectd
      service: name=collectd state=restarted

- hosts: prometheus
  tasks:
    - name: ensure directory exists
      file:
        path: /dmi/data/prometheus
        state: directory
      tags:
        - prometheus
    - name: install config file
      copy:
        src: files/prometheus.yml
        dest: /dmi/data/prometheus/prometheus.yml
      tags:
        - prometheus
    - name: install prometheus
      docker_container:
        name: "prometheus"
        image: "prom/prometheus"
        recreate: true
        ports:
          - "9090:9090"
        volumes:
          - "/dmi/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      tags:
        - prometheus

- hosts: swarmhosts
  tasks:
    - name: install cadvisor
      docker_container:
        name: "cadvisor"
        image: "google/cadvisor:latest"
        restart_policy: always
        restart: true
        volumes:
          - "/\\:/rootfs:ro"
          - "/var/run:/var/run:rw"
          - "/sys:/sys:ro"
          - "/var/lib/docker/:/var/lib/docker:ro"
        ports:
          - "8080:8080"
        command: ["-storage_driver=influxdb", "-storage_driver_db=cadvisor", "-storage_driver_host=influxdb.swarm:8086"]
    - name: install node-exporter
      docker_container:
        name: "node-exporter"
        image: "prom/node-exporter"
        restart_policy: always
        ports:
          - "9100:9100"
        network_mode: host
  tags:
    - cadvisor
    - node-exporter

- hosts: grafana
  tasks:
    - name: install grafana
      docker_container:
        name: grafana
        image: grafana/grafana
        ports:
          - "3000:3000"
#
#- hosts: all
#    - name: install prometheus node-exporter
